# Generated by Django 2.0.3 on 2018-03-22 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='primeiro nome')),
                ('last_name', models.CharField(max_length=128, verbose_name='sobrenome')),
                ('tax_id', models.CharField(max_length=14, verbose_name='cpf')),
                ('phone', models.CharField(max_length=32, verbose_name='telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('influenced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influenced', to='core.Associate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
