# Generated by Django 2.0.3 on 2018-03-22 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180321_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='influenced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influenced', to='core.Associate'),
        ),
    ]
