# Generated by Django 2.0.3 on 2018-03-24 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180321_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associate',
            options={'verbose_name': 'Associado', 'verbose_name_plural': 'Associados'},
        ),
        migrations.RemoveField(
            model_name='associate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='associate',
            name='last_name',
        ),
        migrations.AddField(
            model_name='associate',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data de nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associate',
            name='zipcode',
            field=models.CharField(default='', max_length=32, verbose_name='cep'),
            preserve_default=False,
        ),
    ]
