# Generated by Django 2.0.3 on 2018-03-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180324_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='tax_id',
            field=models.CharField(max_length=14, unique=True, verbose_name='cpf'),
        ),
    ]
