# Generated by Django 2.0.3 on 2018-03-30 13:58
import random
import string

from django.apps import apps
from django.conf import settings
from django.db import migrations


def populate_member_code(apps, schema_editor):
    Associate = apps.get_model('core', 'Associate')
    for a in Associate.objects.all():
        a.member_code = ''.join(random.choices(string.ascii_letters, k=settings.MEMBER_CODE_LENGTH))
        a.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_associate_member_code'),
    ]

    operations = [
        migrations.RunPython(populate_member_code)
    ]
