# Generated by Django 2.0.3 on 2018-04-07 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180330_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='impressions',
            field=models.IntegerField(default=0, verbose_name='impressões'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='by_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversions', to='core.Campaign'),
        ),
    ]
